backend:
  name: git-gateway
  repo: kayla-moz-portfolio
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{year}}-{{month}}-{{day}}-{{title}}/index'
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: work
    label: Work
    folder: src/work
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{year}}-{{month}}-{{day}}-{{title}}/index'
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }
      - label: Images
        name: images
        widget: object
        collapsed: true
        fields:
          - {
              name: image-first,
              label: First image,
              widget: image,
              required: false,
            }
          - {
              name: image-second,
              label: Second image,
              widget: image,
              required: false,
            }
          - {
              name: image-third,
              label: Third image,
              widget: image,
              required: false,
            }
          - {
              name: image-fourth,
              label: Fourth image,
              widget: image,
              required: false,
            }
          - {
              name: image-fifth,
              label: Fifth image,
              widget: image,
              required: false,
            }
          - {
              name: image-sixth,
              label: Sixth image,
              widget: image,
              required: false,
            }
  - name: exhibitions
    label: Exhibitions
    folder: src/exhibitions
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{year}}-{{month}}-{{day}}-{{title}}/index'
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }
